server:
  port: 8081

spring:
  application:
    name: vblog

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.99.100:3306/vblog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
#    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
